baseURL = "https://graphqlfoundation.io"
languageCode = "en-us"
title = "The GraphQL Foundation"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTxt = true

[params]
tagline = "An open and neutral home for the GraphQL community"
description = "An open and neutral home for the GraphQL community to enable widespread adoption and help accelerate development and the surrounding ecosystem"
copyright = "All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](http://www.linuxfoundation.org/privacy) and [Terms of Use](http://www.linuxfoundation.org/terms)."

[params.logos]
hero   = "graphql-foundation.png"
navbar = "graphql-foundation-color.png"
footer = "graphql-icon.svg"
topper = "lf-projects.png"
